export const COLORS = {
  orange:   "#ea580c",
  orangeBg: "#fff7ed",
  coral:    "#dc2626",
  coralBg:  "#fef2f2",
  blue:     "#2563eb",
  blueBg:   "#eff6ff",
  amber:    "#d97706",
  amberBg:  "#fffbeb",
  green:    "#16a34a",
  greenBg:  "#f0fdf4",
  pink:     "#db2777",
  pinkBg:   "#fdf2f8",
  teal:     "#ea580c",
  tealBg:   "#fff7ed",
};

export const SHADOW = "0 10px 30px rgba(28,25,23,0.06), 0 2px 8px rgba(28,25,23,0.03)";

export const S = {
  main:    { display: "flex", flexDirection: "column", gap: 18, flex: 1, minHeight: 0 },
  metricsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 14 },
  metric: { background: "#fff", borderRadius: 18, padding: "16px 18px", boxShadow: SHADOW },
  metricLabel: { fontSize: 11, color: "#78716c", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 },
  metricValue: { fontSize: 22, fontWeight: 700, lineHeight: 1.1 },
  metricSub:   { fontSize: 11, color: "#78716c", marginTop: 4 },
  card:    { background: "#fff", borderRadius: 22, boxShadow: SHADOW, overflow: "hidden", display: "flex", flexDirection: "column", flex: 1, minHeight: 0 },
  cardHdr: { padding: "16px 20px", borderBottom: "1px solid #f5f5f4", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 10 },
  cardTitle:{ fontSize: 14, fontWeight: 600, display: "flex", alignItems: "center", gap: 6, color: "#1c1917" },
  tblWrap: { overflowX: "auto", flex: 1, minHeight: 0, overflowY: "auto" },
  tbl:     { width: "100%", borderCollapse: "collapse", fontSize: 12 },
  th:      { background: "#fafaf9", padding: "10px 14px", textAlign: "left", fontWeight: 600, fontSize: 11, color: "#78716c", textTransform: "uppercase", letterSpacing: "0.05em", whiteSpace: "nowrap", borderBottom: "1px solid #f5f5f4", position: "sticky", top: 0, zIndex: 2 },
  td:      { padding: "10px 14px", borderBottom: "1px solid #f5f5f4", whiteSpace: "nowrap" },
  tdR:     { padding: "10px 14px", borderBottom: "1px solid #f5f5f4", whiteSpace: "nowrap", textAlign: "right", fontVariantNumeric: "tabular-nums" },
  inputSm: { fontSize: 12, padding: "8px 14px", height: 36, borderRadius: 999, border: "none", background: "#f5f5f4", color: "#1c1917", fontFamily: "inherit", outline: "none", boxShadow: "inset 0 1px 2px rgba(0,0,0,0.04)" },
  addBtn:  { padding: "8px 16px", height: 36, border: "none", borderRadius: 999, background: COLORS.orange, cursor: "pointer", fontSize: 12, color: "#fff", fontFamily: "inherit", fontWeight: 600, display: "flex", alignItems: "center", gap: 4, boxShadow: "0 4px 14px rgba(234,88,12,0.3)" },
  modalBg: { position: "fixed", inset: 0, background: "rgba(28,25,23,0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, backdropFilter: "blur(4px)" },
  modal:   { background: "#fff", borderRadius: 24, padding: 24, width: 420, maxWidth: "95vw", maxHeight: "90vh", overflowY: "auto", boxShadow: "0 24px 60px rgba(28,25,23,0.18)" },
  formRow: { marginBottom: 14 },
  formLbl: { display: "block", fontSize: 11, color: "#78716c", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: 5, fontWeight: 600 },
  formInp: { width: "100%", padding: "10px 14px", border: "none", borderRadius: 14, background: "#f5f5f4", color: "#1c1917", fontFamily: "inherit", fontSize: 13, boxSizing: "border-box", outline: "none" },
  btnPrimary:   { padding: "10px 18px", background: COLORS.orange, color: "#fff", border: "none", borderRadius: 999, cursor: "pointer", fontSize: 13, fontFamily: "inherit", fontWeight: 600, boxShadow: "0 4px 14px rgba(234,88,12,0.3)" },
  btnSecondary: { padding: "10px 18px", background: "#f5f5f4", border: "none", borderRadius: 999, cursor: "pointer", fontSize: 13, fontFamily: "inherit", color: "#44403c", fontWeight: 500 },
  empty: { padding: 36, textAlign: "center", color: "#a8a29e", fontSize: 13 },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 },
  searchRow: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },
};
